### ISSUE TITLE
UI bug(?) using ensure with a do block

### ISSUE THREAD

**Issue by pivotal-topher-bullock** [concourse/atc#21]
We're testing out the ensure feature and found some Ui inconsistencies when using it with a do block. It works fine and looks like we'd expect when both tasks in the do block fail or only the first task fails, but the case when the last fails and the first passes looks odd in the UI

![screen shot 2015-07-17 at 11 57 59 am](https://cloud.githubusercontent.com/assets/1895900/8751436/0a9adede-2c7b-11e5-8f41-d848622df7da.png)

Here's the YAML for the pipeline:

```yml
---
resources:

jobs:
  - name: make-it-happen
    plan:
      - do: 
        - task: beep
          config:
            platform: linux
            image: docker:///ubuntu
            run:
              path: /bin/bash
              args: ["-c", "exit 0"]
        - task: boop
          privileged: true
          config:
            platform: linux
            image: docker:///ubuntu
            run:
              path: /bin/bash
              args: ["-c", "exit 1"]
        ensure:
          task: moop
          config:
              platform: linux
              image: docker:///ubuntu
              run:
                path: /bin/bash
                args: ["-c", "ls"]
```
