### ISSUE TITLE
Task inputs/outputs copy/move actions

### ISSUE THREAD

**Issue by aequitas** [concourse/atc#62]
A common pattern is a simple task command which builds artifacts in the source directory. These artifacts then need to be copied/moved out of this directory into a directory which is an `output` because in-/outputs can't be nested. This directory is outside of the source directory, adding the need to modify/wrap the simple command to account for this and making these commands less CI agnostic.

This also applies to `inputs` where the command needs to be (made) aware of the CI directory structure to find the input artifact.

A antipattern I now apply is building tasks like this:

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
  - name: my-repo
  - name: version

outputs:
  - name: dist

run:
  path: /bin/sh
  args:
      - -c
      - cp -v version/version dist/version; /usr/bin/make -C src test build;mv -v src/dist/*.tar.gz dist/
```

My suggestion is to add `actions` to the `inputs`/`outputs` which override the default behaviour of the directory nesting error and allow to copy or move files out.

Example:
```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
- name: my-repo

outputs:
- name: artifact
  copy: my-repo/dist/

run:
  path: my-repo/scripts/test
```` 

`my-repo/scripts/test` would generate a artifact `my-repo/dist/build.tar.gz` which would then be copied to `artifact/build.tar.gz`.

Or possibly support globing to allow artifact extraction without subdirectories:

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: '14.04'

inputs:
- name: my-repo

outputs:
- name: artifact
  copy: my-repo/*.tar.gz

run:
  path: my-repo/scripts/test
```` 

where `my-repo/scripts/test` would generate a artifact `my-repo/build.tar.gz` which would then be copied to `artifact/build.tar.gz`.
